Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/02/2023
Var
// Seção de Declarações das variáveis 
   Nome: Caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Digite seu nome: ")
   leia (Nome)
   escreva ("Muito prazer ",Nome)

Fimalgoritmo